from fastapi import APIRouter, Depends

from app.api.deps import get_current_user
from app.db.models import User


router = APIRouter()


def _coerce_numeric(value: object) -> float | None:
    if isinstance(value, bool):
        return 1.0 if value else 0.0
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        try:
            return float(value)
        except ValueError:
            return None
    return None


def _flip_value(value: object) -> object:
    if isinstance(value, bool):
        return not value
    if isinstance(value, (int, float)):
        return 0 if float(value) > 0 else 1
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered in {"1", "true", "yes", "y", "m", "male"}:
            return "0"
        if lowered in {"0", "false", "no", "n", "f", "female"}:
            return "1"
        return f"not_{value}"
    return value


@router.post("/row")
def explain_row(row: dict, _: User = Depends(get_current_user)) -> dict:
    numeric_features: list[tuple[str, float]] = []
    non_numeric_features: list[str] = []

    for key, value in row.items():
        numeric = _coerce_numeric(value)
        if numeric is None:
            non_numeric_features.append(key)
            continue
        numeric_features.append((key, numeric))

    ranked = sorted(numeric_features, key=lambda item: abs(item[1]), reverse=True)
    top_drivers = [
        {
            "feature": key,
            "value": value,
            "direction": "positive" if value >= 0 else "negative",
        }
        for key, value in ranked[:5]
    ]

    model_score = sum(value for _, value in numeric_features)

    return {
        "explanation": "Feature influence ranking computed from numeric feature magnitude for this row.",
        "model_score_proxy": round(model_score, 4),
        "top_drivers": top_drivers,
        "non_numeric_features": non_numeric_features,
        "row": row,
    }


@router.post("/counterfactual")
def explain_counterfactual(row: dict, sensitive_attribute: str, _: User = Depends(get_current_user)) -> dict:
    if sensitive_attribute not in row:
        return {
            "changed_attribute": sensitive_attribute,
            "outcome_changed": False,
            "message": "Sensitive attribute is not present in the provided row.",
            "row": row,
        }

    original_value = row[sensitive_attribute]
    flipped_value = _flip_value(original_value)
    counterfactual_row = {**row, sensitive_attribute: flipped_value}

    return {
        "changed_attribute": sensitive_attribute,
        "original_value": original_value,
        "counterfactual_value": flipped_value,
        "outcome_changed": None,
        "message": "Counterfactual row generated by flipping the sensitive attribute. Re-score original and counterfactual rows with your model to quantify fairness impact.",
        "row": row,
        "counterfactual_row": counterfactual_row,
    }
